Create User C##FERRETERIA IDENTIFIED BY Admin2025;
ALTER USER C##FERRETERIA DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO C##FERRETERIA;
GRANT CREATE VIEW TO C##FERRETERIA;
GRANT CREATE TRIGGER TO C##FERRETERIA;
GRANT CREATE PROCEDURE TO C##FERRETERIA;
GRANT CREATE SEQUENCE TO C##FERRETERIA;

--GRANT EXECUTE ON SYS.DBMS_CRYPTO TO C##FERRETERIA;
