
CREATE USER FERRETERIA IDENTIFIED BY Admin2025;

ALTER USER FERRETERIA DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO FERRETERIA;
GRANT CREATE VIEW TO FERRETERIA;
GRANT CREATE TRIGGER TO FERRETERIA;
GRANT CREATE PROCEDURE TO FERRETERIA;
GRANT CREATE SEQUENCE TO FERRETERIA;
GRANT CREATE ROLE TO FERRETERIA; 
GRANT CREATE USER TO FERRETERIA;
GRANT ALTER USER TO FERRETERIA;
GRANT DROP USER TO FERRETERIA;

-- (Conectado como SYS AS SYSDBA en XEPDB1)

GRANT CONNECT, RESOURCE TO FERRETERIA WITH ADMIN OPTION;

GRANT EXECUTE ON SYS.DBMS_CRYPTO TO FERRETERIA;

show con_name;

CREATE OR REPLACE TRIGGER trg_app_actualizar_last_login
AFTER LOGON ON DATABASE
BEGIN
    -- Ahora SYS sí tiene permiso para ejecutar este UPDATE
    UPDATE FERRETERIA.USUARIO
    SET last_login = SYSTIMESTAMP
    WHERE username = USER; 
    
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/