-- (Conectado como FERRETERIA en XEPDB1)

-- Rol para usuarios que solo pueden vender
CREATE ROLE ROL_VENDEDOR_DB;

-- Rol para usuarios que manejan el inventario
CREATE ROLE ROL_BODEGUERO_DB;

-- Rol para usuarios de contabilidad (pagos)
CREATE ROLE ROL_CONTADOR_DB;

-- Rol para el Administrador de la APLICACIÓN
-- (No es el DBA, es el usuario que crea otros usuarios y ve todo)
CREATE ROLE ROL_ADMIN_APP_DB;

-- (Conectado como FERRETERIA en XEPDB1)

-- === Permisos para VENDEDOR ===
GRANT SELECT ON CLIENTE TO ROL_VENDEDOR_DB;
GRANT SELECT ON PRODUCTO TO ROL_VENDEDOR_DB;
GRANT SELECT ON VENDEDOR TO ROL_VENDEDOR_DB;
GRANT SELECT, INSERT ON FACTURA TO ROL_VENDEDOR_DB;
GRANT SELECT, INSERT ON FACTURA_DETALLE TO ROL_VENDEDOR_DB;
GRANT SELECT, INSERT ON NOTA_CREDITO TO ROL_VENDEDOR_DB;
GRANT SELECT, INSERT ON NOTA_CREDITO_DETALLE TO ROL_VENDEDOR_DB;
-- Permiso para ver sus reportes
GRANT SELECT ON V_TOP_CLIENTES_SUCURSAL TO ROL_VENDEDOR_DB;
GRANT SELECT ON V_TOP_VENDEDORES_REGION TO ROL_VENDEDOR_DB;

-- === Permisos para BODEGUERO ===
GRANT SELECT ON PRODUCTO TO ROL_BODEGUERO_DB;
GRANT SELECT ON PROVEEDOR TO ROL_BODEGUERO_DB;
GRANT SELECT ON SUCURSAL TO ROL_BODEGUERO_DB;
GRANT SELECT, INSERT, UPDATE ON EXISTENCIAS_SUCURSAL TO ROL_BODEGUERO_DB;
GRANT SELECT, INSERT ON COMPRA TO ROL_BODEGUERO_DB;
GRANT SELECT, INSERT ON COMPRA_DETALLE TO ROL_BODEGUERO_DB;
-- Permiso para ver su reporte
GRANT SELECT ON V_RESUMEN_INVENTARIO TO ROL_BODEGUERO_DB;

-- === Permisos para CONTADOR ===
GRANT SELECT ON FACTURA TO ROL_CONTADOR_DB;
GRANT SELECT ON COMPRA TO ROL_CONTADOR_DB;
GRANT SELECT, INSERT ON PAGOS_VENTAS TO ROL_CONTADOR_DB;
GRANT SELECT, INSERT ON PAGOS_COMPRAS TO ROL_CONTADOR_DB;
-- Permiso para ver reportes financieros
GRANT SELECT ON V_TOP_CLIENTES_SUCURSAL TO ROL_CONTADOR_DB;

-- === Permisos para ADMIN_APP ===
-- (Este rol debe poder ver todo y administrar usuarios)
GRANT SELECT ON AUDITORIA_GENERAL TO ROL_ADMIN_APP_DB;
GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIO TO ROL_ADMIN_APP_DB;
GRANT SELECT, INSERT, UPDATE, DELETE ON ROLES_APLICACION TO ROL_ADMIN_APP_DB;
-- Le damos acceso a todas las vistas de reportes
GRANT SELECT ON V_TOP_CLIENTES_SUCURSAL TO ROL_ADMIN_APP_DB;
GRANT SELECT ON V_TOP_VENDEDORES_REGION TO ROL_ADMIN_APP_DB;
GRANT SELECT ON V_RESUMEN_INVENTARIO TO ROL_ADMIN_APP_DB;
-- Permiso para ejecutar los paquetes
GRANT EXECUTE ON PKG_SEGURIDAD TO ROL_ADMIN_APP_DB;
GRANT EXECUTE ON PKG_REPORTES TO ROL_ADMIN_APP_DB;